- name: run update
  shell: apt-get update

- name: install prerequisites
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - python3
    - python3-pip
    - nginx
    - gunicorn

- name: create www folder
  file:
    path: /var/www
    state: directory

- name: Clone the repo
  git:
    repo: 'https://github.com/inno-asiimwe/bucketlist-api-gcp'
    dest: /var/www/bucketlist-api-gcp
    clone: yes

- name: Copy env file
  copy:
    src: ../files/flask/.env
    dest: /var/www/bucketlist-api-gcp/.env

- name: Copy start up script
  copy:
    src: ../files/flask/start.sh
    dest: /var/www/bucketlist-api-gcp/start.sh
    mode: u+rwx

- name:
  pip:
    name: virtualenv
    state: present

- name: creat virtualenv
  command: virtualenv /var/www/env -p python3 creates="/var/www/env"

- name: Install requirements
  pip:
    requirements: /var/www/bucketlist-api-gcp/requirements.txt
    virtualenv: /var/www/env